import type { AotdPlan } from "./types.js";

export interface FewShotExample {
  input: string;
  output: AotdPlan;
}

export const aotdFewShotExamples: FewShotExample[] = [
  {
    input: [
      "问题一·情绪消耗源：被看见认可",
      "问题二·情绪需求：把开心放大",
      "问题三·情绪意境：彩虹天光",
    ].join("\n"),
    output: {
      consumptionSource: "被看见认可",
      emotionalNeed: "把开心放大",
      emotionalImagery: "彩虹天光",
      userIntent: "把今天被认真看见的那一下继续留在身上。",
      todayStateSummary: "今晚的你，不是在修复自己，而是在守住一个难得亮起来的瞬间；你想把这点开心和轻盈再多留一会儿。",
      moodSignals: ["被看见", "轻盈", "开心", "自我确认"],
      sceneSignals: ["彩虹", "天光", "下班后的亮度"],
      objectiveSignals: ["延长高光时刻", "放大开心", "保留轻盈感"],
      constraints: ["避免太苦", "不要突然过丧", "保留高级感"],
      playlistStrategy: "先锁定 Celebrate / bright 方向，再用彩虹、天光、被看见这些信号筛选更有亮度和流动感的歌。",
      queryHints: ["celebrate", "bright", "recognition", "rainbow glow", "confident pop"],
      explanationStyle: "像懂状态的心理咨询师，先识别亮点，再帮用户把开心留住。",
      uncertainty: [],
    },
  },
  {
    input: [
      "问题一·情绪消耗源：信息惊喜",
      "问题二·情绪需求：去探索一下",
      "问题三·情绪意境：书店角落",
    ].join("\n"),
    output: {
      consumptionSource: "信息惊喜",
      emotionalNeed: "去探索一下",
      emotionalImagery: "书店角落",
      userIntent: "顺着今天被点亮的好奇心，再往前走一点。",
      todayStateSummary: "你现在不是需要被安抚，而是想保留那股“我还想继续看下去”的心情；书店角落这类安静但不空的空间，正适合让好奇心慢慢展开。",
      moodSignals: ["好奇", "新鲜感", "注意力被点亮"],
      sceneSignals: ["书店", "展览", "安静角落", "城市漫游"],
      objectiveSignals: ["满足新鲜感", "保留探索欲", "让心往外打开"],
      constraints: ["避免太保守", "不要太闷", "保留发现感"],
      playlistStrategy: "优先 Explore 方向，同时保留书店、展览、安静角落这些 scene 信号，让歌单更像一场城市里的小型漫游。",
      queryHints: ["explore", "bookstore", "gallery", "fresh", "city roam"],
      explanationStyle: "像生活方式编辑和心理咨询师的结合体，温柔但有判断力。",
      uncertainty: [],
    },
  },
  {
    input: [
      "问题一·情绪消耗源：身体疲惫",
      "问题二·情绪需求：轻轻放松",
      "问题三·情绪意境：街角花店",
    ].join("\n"),
    output: {
      consumptionSource: "身体疲惫",
      emotionalNeed: "轻轻放松",
      emotionalImagery: "街角花店",
      userIntent: "先让身体下班，再让情绪慢慢回暖。",
      todayStateSummary: "从这三个选择看，你今晚更像是累，不是丧；你需要的不是被立刻打鸡血，而是在一个像街角花店这样有生活温度的场景里，慢慢把自己放下来。",
      moodSignals: ["身体疲惫", "回暖", "想被温柔安放"],
      sceneSignals: ["花店", "街角", "晚风", "生活感"],
      objectiveSignals: ["卸力", "缓下来", "恢复呼吸感"],
      constraints: ["不要太炸", "避免过度煽情", "保留温柔"],
      playlistStrategy: "优先 Recovery / Companion 方向，用低刺激、带生活感和温度感的作品把疲惫慢慢接住。",
      queryHints: ["recovery", "flower shop", "warm", "late walk", "soft comfort"],
      explanationStyle: "像会先接住你状态的心理咨询师，不急着鼓励，先让你安全落地。",
      uncertainty: [],
    },
  },
  {
    input: [
      "问题一·情绪消耗源：沟通交流",
      "问题二·情绪需求：清空大脑",
      "问题三·情绪意境：咖啡店窗边",
    ].join("\n"),
    output: {
      consumptionSource: "沟通交流",
      emotionalNeed: "清空大脑",
      emotionalImagery: "咖啡店窗边",
      userIntent: "把今天被人和信息打散的心神重新收回来。",
      todayStateSummary: "你现在最缺的不是热闹，而是一点内在留白；咖啡店窗边这种有陪伴感但不过度打扰的空间，正适合帮你把脑内弹窗一层层关掉。",
      moodSignals: ["信息密度高", "脑噪", "轻微疲惫", "需要安静"],
      sceneSignals: ["咖啡店", "窗边", "城市夜晚"],
      objectiveSignals: ["清理脑噪", "恢复专注", "留一点白"],
      constraints: ["不要歌词过密", "避免太吵", "不要情绪过猛"],
      playlistStrategy: "从 Reflection / Recovery 方向切入，但保留一点窗边和城市夜色的空气感，让安静不等于无聊。",
      queryHints: ["clear mind", "coffee shop", "window", "soft night", "reflection"],
      explanationStyle: "像善于捕捉疲惫来源的咨询师，语气克制但理解很到位。",
      uncertainty: [],
    },
  },
  {
    input: [
      "问题一·情绪消耗源：成就推进",
      "问题二·情绪需求：继续发光",
      "问题三·情绪意境：公路车窗",
    ].join("\n"),
    output: {
      consumptionSource: "成就推进",
      emotionalNeed: "继续发光",
      emotionalImagery: "公路车窗",
      userIntent: "把今天的推进感继续转成一种更有线条的自我确认。",
      todayStateSummary: "今晚的你更像在回看今天一路推进出来的手感；你不是需要安慰，而是想在公路车窗这种带移动感的场景里，把自己的状态继续提着、继续亮着。",
      moodSignals: ["推进感", "成就感", "自我确认", "在线"],
      sceneSignals: ["公路", "车窗", "路灯", "流动感"],
      objectiveSignals: ["延续状态", "放大自信", "保持线条感"],
      constraints: ["避免太软塌", "不要太土味", "保留都市感"],
      playlistStrategy: "锁定 Growth / Celebrate 的交界，再用 road window、city drive、confident 这些线索挑出更有步伐感和移动感的歌。",
      queryHints: ["growth", "confident", "road window", "city drive", "stylish groove"],
      explanationStyle: "像时尚买手一样，强调氛围与气场。",
      uncertainty: [],
    },
  },
  {
    input: [
      "问题一·情绪消耗源：关系连接",
      "问题二·情绪需求：有人分享",
      "问题三·情绪意境：夜市灯串",
    ].join("\n"),
    output: {
      consumptionSource: "关系连接",
      emotionalNeed: "有人分享",
      emotionalImagery: "夜市灯串",
      userIntent: "想把今天和别人一起过完，而不是自己默默收掉。",
      todayStateSummary: "你现在并不想一个人把情绪消化干净，而是更想保留那种有人能一起感受的热度；夜市灯串这种有烟火气的场景，说明你想要的是陪伴感和生活感，而不是纯粹独处。",
      moodSignals: ["连接感", "想分享", "被生活托住", "有人一起会更完整"],
      sceneSignals: ["夜市", "灯串", "烟火气", "城市夜晚"],
      objectiveSignals: ["增加陪伴感", "让状态外扩", "保留生活热度"],
      constraints: ["避免过度孤独", "不要太冷", "保留烟火气"],
      playlistStrategy: "优先 Companion / Celebrate 交界，用有生活热度和轻社交感的作品承接“想分享”的需求。",
      queryHints: ["companion", "night market", "warm lights", "share", "city night"],
      explanationStyle: "像很懂人际与情绪连接的咨询师，先看见连接需求，再给有温度的陪伴。",
      uncertainty: [],
    },
  },
];
