import type { SongDocument } from "./types.js";

function withDefaults(
  song: Pick<SongDocument, "id" | "title" | "artist" | "language" | "energy" | "moods" | "scenes" | "tags">,
): SongDocument {
  return {
    ...song,
    primaryNeed: "",
    genre: "",
    needTags: [],
    sceneTags: [...song.scenes],
    weatherTags: [],
    timeTags: [],
    cliKeyword: `${song.title} ${song.artist}`,
    isPlayable: false,
    idStatus: "Pending",
    reviewStatus: "Demo",
  };
}

export const demoSongCatalog: SongDocument[] = [
  withDefaults({
    id: "song_001",
    title: "Best Part",
    artist: "Daniel Caesar & H.E.R.",
    language: "en",
    energy: "low",
    moods: ["温柔", "松弛", "被接住"],
    scenes: ["夜晚", "独处", "散步"],
    tags: ["soft vocal", "warm", "healing", "late night"],
  }),
  withDefaults({
    id: "song_002",
    title: "Nights",
    artist: "Frank Ocean",
    language: "en",
    energy: "medium",
    moods: ["都市感", "情绪流动", "克制性感"],
    scenes: ["夜晚", "通勤", "赴约路上"],
    tags: ["city walk", "night", "stylish", "cool pop"],
  }),
  withDefaults({
    id: "song_003",
    title: "Holocene",
    artist: "Bon Iver",
    language: "en",
    energy: "low",
    moods: ["留白", "安静", "恢复感受力"],
    scenes: ["下雨天", "独处", "窗边"],
    tags: ["gentle healing", "soft melancholy", "quiet"],
  }),
  withDefaults({
    id: "song_004",
    title: "Sunset Rollercoaster",
    artist: "My Jinji",
    language: "en",
    energy: "medium",
    moods: ["轻盈", "慵懒", "氛围感"],
    scenes: ["小聚", "傍晚", "居家"],
    tags: ["lounge", "background music", "warm chill", "soft upbeat"],
  }),
  withDefaults({
    id: "song_005",
    title: "505",
    artist: "Arctic Monkeys",
    language: "en",
    energy: "medium",
    moods: ["克制", "夜色感", "故事性"],
    scenes: ["夜晚", "散步", "城市"],
    tags: ["night walk", "indie", "cool", "city"],
  }),
  withDefaults({
    id: "song_006",
    title: "Get You",
    artist: "Daniel Caesar ft. Kali Uchis",
    language: "en",
    energy: "medium",
    moods: ["魅力", "温热", "亲密感"],
    scenes: ["约会前", "夜晚", "独处"],
    tags: ["date night", "confident", "warm", "stylish groove"],
  }),
  withDefaults({
    id: "song_007",
    title: "Breathe",
    artist: "Télépopmusik",
    language: "en",
    energy: "low",
    moods: ["空气感", "湿润", "松弛"],
    scenes: ["下雨天", "夜晚", "室内"],
    tags: ["rainy day", "dream pop", "wet air", "ambient"],
  }),
  withDefaults({
    id: "song_008",
    title: "Awake",
    artist: "Tycho",
    language: "instrumental",
    energy: "medium",
    moods: ["专注", "流动", "轻推进"],
    scenes: ["写作", "工作", "整理房间"],
    tags: ["focus", "light instrumental", "steady groove", "productive"],
  }),
  withDefaults({
    id: "song_009",
    title: "Pink + White",
    artist: "Frank Ocean",
    language: "en",
    energy: "low",
    moods: ["透气", "柔软", "回暖"],
    scenes: ["下班后", "夜晚", "独处"],
    tags: ["soft comfort", "wind down", "gentle healing", "warm indie"],
  }),
  withDefaults({
    id: "song_010",
    title: "Tadow",
    artist: "Masego & FKJ",
    language: "instrumental",
    energy: "medium",
    moods: ["自信", "松弛", "都市感"],
    scenes: ["赴约路上", "小聚", "夜晚"],
    tags: ["confident", "groove", "stylish", "dinner vibe"],
  }),
  withDefaults({
    id: "song_011",
    title: "Weightless",
    artist: "Marconi Union",
    language: "instrumental",
    energy: "low",
    moods: ["排水", "放松", "身心回落"],
    scenes: ["下班后", "恢复期", "夜晚"],
    tags: ["cool down", "wind down", "recovery vibe", "calm"],
  }),
  withDefaults({
    id: "song_012",
    title: "Riverside",
    artist: "Agnes Obel",
    language: "en",
    energy: "low",
    moods: ["文学感", "安静", "细腻"],
    scenes: ["写作", "清晨", "独处"],
    tags: ["literary", "quiet focus", "ambient folk", "minimal vocal"],
  }),
];
